version: '3.8'

networks:
  laravel_docker_sample:

services:
  nginx:
    container_name: sample_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - laravel_docker_sample
    depends_on:
      - php
    
  php:
    container_name: sample_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes: 
      - ./:/var/www/html
    networks:
      - laravel_docker_sample
    depends_on:
      - mysql

  mysql:
    container_name: sample_mysql
    image: mysql
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel_docker_sample
  
  # redis:
  #   container_name: sample_redis
  #   image: "redis"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./docker/redis:/data"
  #   networks:
  #     - laravel_docker_sample

  node:
    container_name: sample_node
    build: ./.docker/node
    tty: true
    volumes:
      - ./:/var/www/html/app
    networks:
      - laravel_docker_sample